name: redux_basics_adventure
description: Explore the basics of the redux architecture in Flutter.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_redux: ^0.8.2
  redux: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
